DROP DATABASE IF EXISTS db_ium;
CREATE DATABASE IF NOT EXISTS db_ium CHARACTER SET utf8;

USE db_ium;

CREATE TABLE tbl_imgs (
    ID_IMG INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    IMG MEDIUMBLOB NOT NULL,
    IP_ADDRESS VARCHAR(50) NOT NULL,
    DATE_CREATION DATETIME NOT NULL DEFAULT now(),
    DATE_DISABLED DATETIME
) ENGINE = MyISAM;

CREATE VIEW vw_imgs AS
    SELECT IMG FROM tbl_imgs WHERE DATE_DISABLED IS NULL;

DROP USER IF EXISTS 'user_api'@'localhost';
CREATE USER IF NOT EXISTS 'user_api'@'localhost' IDENTIFIED BY 'peluza';

GRANT select,insert ON db_ium.* TO 'user_api'@'localhost';
FLUSH PRIVILEGES;